
Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10


In [2]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8..... 10]) 
print(ds)


SyntaxError: ignored

Write a Pandas program to convert a Panda module Series to Python list and its type.



In [3]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [4]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [5]:
#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)



Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [6]:
#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


In [7]:
#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [8]:
#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']

import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


In [9]:
# Write a Pandas program to convert a given Series to an array.
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


In [11]:
#Write a Pandas program to sort a given Series.
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)



Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


In [12]:
#Write a Pandas program to add some data to an existing Series.

import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


In [13]:
#Write a Pandas program to create a subset of a given series based on value and condition.

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


In [14]:
#Write a Pandas program to change the order of index of a given series.
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [15]:
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())



Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


In [16]:
#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [ ]:
#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)


In [ ]:
#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv

import pandas as pd
import numpy as np
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)

#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)


In [ ]:
#Write a Pandas program to display the first 10 rows of the DataFrame.
import pandas as pd
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)


In [19]:
#Write a NumPy program to generate five random numbers from the normal distribution.
import numpy as np
x = np.random.normal(size=5)
print(x)


[-0.16120538 -0.52360377  1.05032321 -1.07650025 -0.47268028]


In [20]:
#Write a NumPy program to generate six random integers between 10 and 30
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[19 13 11 25 23 28]


In [21]:
#Write a NumPy program to create a 3x3x3 array with random values.
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.0129849  0.94076858 0.71155363]
  [0.70050625 0.74375053 0.84488753]
  [0.09039843 0.02231311 0.8855969 ]]

 [[0.59148134 0.24119884 0.11546654]
  [0.58209459 0.58815575 0.18083224]
  [0.7587112  0.89013353 0.81486243]]

 [[0.2239089  0.15382077 0.43712492]
  [0.09457531 0.29502688 0.59928966]
  [0.40296788 0.48655821 0.14583784]]]


In [22]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.16564034 0.9774214  0.04360135 0.25982055 0.47811087]
 [0.10822743 0.34089612 0.17635684 0.56826264 0.56535484]
 [0.02795698 0.90197184 0.96608427 0.41252244 0.16586853]
 [0.00921908 0.246325   0.64728201 0.0527755  0.26338833]
 [0.04947637 0.72566477 0.30984642 0.70869976 0.4609745 ]]
Minimum and Maximum Values:
0.009219080197510499 0.9774213962982549


In [23]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)



Original array: 
[[0.41863681 0.79999105 0.13356958 0.24011299]
 [0.54198764 0.41395213 0.33569853 0.90052574]
 [0.17741732 0.69960409 0.11957763 0.95053953]
 [0.59232211 0.48723986 0.8595926  0.43737213]
 [0.19125517 0.98585308 0.29261951 0.88725068]
 [0.79022087 0.85304679 0.1453171  0.0821232 ]
 [0.96389146 0.78986306 0.50001522 0.89693462]
 [0.34280732 0.93404538 0.1672224  0.95482371]
 [0.7685045  0.71923316 0.19738608 0.83170087]
 [0.21116068 0.34618517 0.49588404 0.90269705]]
First 5 rows of the above array:
[[0.41863681 0.79999105 0.13356958 0.24011299]
 [0.54198764 0.41395213 0.33569853 0.90052574]
 [0.17741732 0.69960409 0.11957763 0.95053953]
 [0.59232211 0.48723986 0.8595926  0.43737213]
 [0.19125517 0.98585308 0.29261951 0.88725068]]
First 3 columns of the above array:
[[0.41863681 0.79999105 0.13356958 0.24011299]
 [0.54198764 0.41395213 0.33569853 0.90052574]
 [0.17741732 0.69960409 0.11957763 0.95053953]
 [0.59232211 0.48723986 0.8595926  0.43737213]
 [0.19125517 0.9858

In [24]:
#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[8 4 6 0 3 9 2 1 5 7]
Same result using permutation():
[5 4 1 2 7 0 9 3 8 6]


In [27]:
#Write a NumPy program to create a random integer nos of size 10 and sort it.

import numpy as np
x=np.arange(10)
np.random.random(x)
print (x)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
#Write a NumPy program to create a random integer nos of size 10 and sort it.

import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)




[6 8 5 2 1 3 4 7 9 0]
[0 1 2 3 4 5 6 7 8 9]
